# Generated by Django 5.2.9 on 2025-12-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Division Admin'), ('STAFF', 'Staff'), ('FACULTY', 'Faculty/Stakeholder')], default='FACULTY', max_length=20),
        ),
    ]
