# Generated by Django 6.0 on 2025-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Division Admin'), ('STAFF', 'Staff'), ('FACULTY', 'Faculty/Stakeholder')], default='STAFF', max_length=50),
        ),
    ]
