# Generated by Django 5.2.9 on 2025-12-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('MEETING', 'Meeting'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('MAINTENANCE', 'Maintenance')], max_length=50, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date'], name='events_even_date_5e8e1c_idx'), models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'), models.Index(fields=['-created_at'], name='events_even_created_7af6de_idx')],
            },
        ),
    ]
