# Generated by Django 5.2.9 on 2025-12-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_event_t_a87b5c_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
    ]
