# Generated by Django 5.2.9 on 2025-12-05 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(help_text='Department/Unit name', max_length=255)),
                ('publications_count', models.IntegerField(default=0, help_text='Number of publications')),
                ('service_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Total service hours', max_digits=10)),
                ('trainings_attended', models.IntegerField(default=0, help_text='Number of trainings attended')),
                ('period_start', models.DateField(help_text='Start date of the activity period')),
                ('period_end', models.DateField(help_text='End date of the activity period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty Activities',
                'ordering': ['-period_end', 'faculty'],
                'indexes': [models.Index(fields=['faculty', 'period_start', 'period_end'], name='reports_fac_faculty_690edc_idx'), models.Index(fields=['unit'], name='reports_fac_unit_d4a99a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='FACULTY_ACTIVITY', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('unit_filter', models.CharField(blank=True, help_text='Filter by unit/event type', max_length=255, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(blank=True, help_text='Cached report data', null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['-generated_at'], name='reports_rep_generat_fa1e6b_idx'), models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx')],
            },
        ),
    ]
