# Generated by Django 5.2.9 on 2025-12-05 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('communicationID', models.AutoField(primary_key=True, serialize=False, verbose_name='Communication ID')),
                ('type', models.CharField(choices=[('CIRCULAR', 'Circular'), ('MEMO', 'Memo'), ('EVENT', 'Event'), ('DOCUMENT', 'Document')], max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('target_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Department')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="List of target roles (e.g., ['ADMIN', 'STAFF', 'FACULTY'])", verbose_name='Target Roles')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_communications', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('commID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='circular', serialize=False, to='communications.communication', verbose_name='Communication ID')),
                ('reqs_ack', models.BooleanField(default=False, verbose_name='Requires Acknowledgment')),
            ],
            options={
                'verbose_name': 'Circular',
                'verbose_name_plural': 'Circulars',
            },
        ),
        migrations.CreateModel(
            name='CommunicationDocument',
            fields=[
                ('commID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='document', serialize=False, to='communications.communication', verbose_name='Communication ID')),
                ('document_ID', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document ID')),
                ('route_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Route To')),
            ],
            options={
                'verbose_name': 'Communication Document',
                'verbose_name_plural': 'Communication Documents',
            },
        ),
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('commID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event', serialize=False, to='communications.communication', verbose_name='Communication ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Communication Event',
                'verbose_name_plural': 'Communication Events',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('commID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memo', serialize=False, to='communications.communication', verbose_name='Communication ID')),
                ('reqs_ack', models.BooleanField(default=False, verbose_name='Requires Acknowledgment')),
            ],
            options={
                'verbose_name': 'Memo',
                'verbose_name_plural': 'Memos',
            },
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['-created_at'], name='communicati_created_9249a2_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['type'], name='communicati_type_d0ab61_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['published_at'], name='communicati_publish_97ef5c_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['target_department'], name='communicati_target__c7cadd_idx'),
        ),
    ]
