# Generated by Django 5.2.9 on 2025-12-05 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circular_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Circular ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reqs_ack', models.BooleanField(default=False, verbose_name='Requires Acknowledgment')),
                ('target_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Department')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="List of target roles (e.g., ['ADMIN', 'STAFF', 'FACULTY'])", verbose_name='Target Roles')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_circulars', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Circular',
                'verbose_name_plural': 'Circulars',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='memos_circu_created_40d6f7_idx'), models.Index(fields=['circular_id'], name='memos_circu_circula_64df65_idx'), models.Index(fields=['published_at'], name='memos_circu_publish_e7a214_idx'), models.Index(fields=['target_department'], name='memos_circu_target__6ae2b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Memo ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reqs_ack', models.BooleanField(default=False, verbose_name='Requires Acknowledgment')),
                ('target_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Department')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="List of target roles (e.g., ['ADMIN', 'STAFF', 'FACULTY'])", verbose_name='Target Roles')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_memos', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Memo',
                'verbose_name_plural': 'Memos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='memos_memo_created_62414f_idx'), models.Index(fields=['memo_id'], name='memos_memo_memo_id_2151df_idx'), models.Index(fields=['published_at'], name='memos_memo_publish_86c559_idx'), models.Index(fields=['target_department'], name='memos_memo_target__8903c3_idx')],
            },
        ),
    ]
