# Generated by Django 5.2.9 on 2025-12-05 10:22

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('document_type', models.CharField(choices=[('PUBLICATION', 'Publication'), ('MEMOS', 'Memos'), ('AWARDS', 'Awards')], default='MEMOS', max_length=50)),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Public'), ('PERMITTED', 'Permitted'), ('RESTRICTED', 'Restricted')], default='RESTRICTED', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'), models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['access_level'], name='documents_d_access__2eb685_idx')],
            },
        ),
    ]
