# Generated by Django 5.2.9 on 2025-12-05 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_documen_40c475_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_access__2eb685_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.AddField(
            model_name='document',
            name='route_to',
            field=models.CharField(blank=True, help_text='The receiving end of the document', max_length=255, null=True, verbose_name='Route To'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['route_to'], name='documents_d_route_t_1c5e23_idx'),
        ),
    ]
